on: push
name: build
jobs:
    build:
        name: build app
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.11.1]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm install && npm run build
            - name: update github
              run: git add . && git commit -am "build a project" && git remote add origin https://github.com/joaquinStrada/extraer-color.git && git push origin main
              
            