on: push
name: build
jobs:
    build:
        name: build app
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.11.1]
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm install && npm run build
            - name: Create repo local
              run: rm -rf .git && cd build && git init
            - name: configure github
              run: git config --global user.email ${{ secrets.email }} && git config --global user.name ${{ secrets.name }} && git config --global user.password ${{ secrets.password }}
            - name: Create a new branch
              run: git branch -M build
            - name: add files
              run: git add .
            - name: create commit
              run: git commit -am "build to project"
            - name: add remote
              run: git remote add origin https://github.com/joaquinStrada/extraer-color.git
            - name: push on github
              run: git bush origin build
              
            